id: P4746B780
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA21492
  instance_id: http://purl.bdrc.io/resource/IE21492
  collection_id: http://purl.bdrc.io/resource/PR0ET006
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ཆོས་འབྱུང་བསྟན་པའི་ཉི་མ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P5200
  publisher: PalriParkhang
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    88aa291044a7437a99c68d5909402fa5:
      title: ༡༽༄།ཆོས་འབྱུང་བསྟན་པའི་ཉི་མ་ཞེས་བྱ་བ་བཞུགས་སོ།་།༢༽༄༅།ཨོཾ་སྭ་སྟི།ཆོས་འབྱུང་བསྟན་པའི་ཉི་མ་ཞེས་བྱ་བ།སངས་རྒྱས་དང་བྱང་ཆུབ་སེམས་དཔའ་ཐ
      volume_number: 1
      base_file: UT21492_001_0001.txt
      reference: http://purl.bdrc.io/resource/VL9B7FCD46F8DA865C
      image_group: null
      quality: null
  reproductionOf:
  - http://purl.bdrc.io/resource/W21492
  - http://purl.bdrc.io/resource/MW21492
created_at: '2021-12-22T11:06:06.374688'
last_modified_at: '2021-12-22T11:06:06.374693'
statistics:
  total_words: 92793
  total_non_words: 10190
quality:
  non_words_ratio: 0.11
